
import { Product, Category, BlogPost, Testimonial, Banner, AppSettings } from './types';

export const TRANSLATIONS = {
  en: {
    home: "Home",
    shop: "Shop",
    blog: "Blog",
    about: "About",
    contact: "Contact",
    cart: "Cart",
    wishlist: "Wishlist",
    addToCart: "Add to Cart",
    buyNow: "Buy Now",
    newArrival: "NEW ARRIVAL",
    offer: "OFFER",
    bestSellers: "Best Sellers",
    newArrivals: "New Arrivals",
    categories: "Categories",
    allProducts: "All Products",
    searchPlaceholder: "Search products...",
    sortBy: "Sort By",
    newest: "Newest First",
    priceLowHigh: "Price: Low to High",
    priceHighLow: "Price: High to Low",
    subtotal: "Subtotal",
    shipping: "Shipping",
    orderTotal: "Order Total",
    confirmOrder: "Confirm Order",
    insideDhaka: "Inside Dhaka",
    outsideDhaka: "Outside Dhaka",
    customerReview: "Customer Reviews",
    description: "Description",
    deliveryInfo: "Delivery Information",
    save: "Save",
    saveMoney: "Save ৳",
    backToBrowsing: "Back to browsing",
    youMayAlsoLike: "You May Also Like",
    viewAll: "View All",
    heroBadge: "New Collection 2025",
    heroTitle: "Illuminate Your Living Space",
    heroSubtitle: "Discover a curated collection of premium lighting and decor that turns every house into a dream home.",
    shopNow: "Shop Now",
    ourStory: "Our Story",
    fastDelivery: "Fast Delivery",
    acrossBD: "Across Bangladesh",
    qualityMaterials: "Quality Materials",
    handpicked: "Handpicked items",
    happyCustomers: "Happy Customers",
    satisfaction: "Satisfaction guaranteed",
    whyChoose: "Why Brightify BD?",
    learnMore: "Learn More",
    readMore: "Read More",
    readyToTransform: "Ready to transform your home?",
    browseCollection: "Browse Collection",
    getInTouch: "Get in Touch",
    ourCollection: "Our Collection",
    discoveryText: "Discover premium decoration pieces for your home.",
    noProductsFound: "No products found matching your filters.",
    clearFilters: "Clear all filters",
    shoppingCart: "Shopping Cart",
    emptyCart: "Your cart is empty",
    emptyCartText: "Looks like you haven't added any elegant pieces to your cart yet.",
    emptyWishlist: "Your wishlist is empty",
    emptyWishlistText: "Save your favorite items here to find them later and add them to your collection.",
    startShopping: "Start Shopping",
    orderDetails: "Order Details",
    fullName: "Full Name",
    phoneNumber: "Phone Number",
    district: "District",
    fullAddress: "Full Address",
    paymentMethod: "Payment Method",
    cod: "Cash on Delivery",
    bkash: "Bkash",
    nagad: "Nagad",
    sendMoneyTo: "Please Send Money to",
    verifyTransaction: "Our team will verify your transaction shortly.",
    orderPlaced: "Order Placed Successfully!",
    orderPlacedText: "Thank you for shopping with us. We've received your order and will contact you shortly to confirm.",
    backToShop: "Back to Shop",
    productNotFound: "Product Not Found",
    productNotFoundText: "The item you are looking for might have been moved or removed.",
    reviewsCount: "Reviews",
    postedBy: "Posted by",
    on: "on",
    shippingInfo: "Shipping Information",
    note: "Note",
    fragileNote: "Fragile items like domes and mirrors are handled with extra care and multi-layer bubble wrapping to ensure they reach you in perfect condition.",
    getInTouchText: "Have questions about our decor? Our styling experts are here to help you create your dream home.",
    contactInfo: "Contact Information",
    phoneLabel: "Phone",
    emailLabel: "Email",
    officeAddress: "Office Address",
    nameLabel: "Name",
    messageLabel: "Message",
    sending: "Sending...",
    sendMessage: "Send Message",
    messageSent: "Message Sent!",
    messageSentText: "We've received your message and will get back to you within 24 hours.",
    sendAnother: "Send another message",
    aboutTitle: "About Brightify BD",
    aboutText: "We are a Dhaka-based premium home decoration store. Our mission is to bring elegance and light to every corner of your home through carefully curated designs and high-quality materials.",
    inspirationTitle: "Inspiration & Design",
    inspirationSubtitle: "Expert tips and stories to help you craft your perfect sanctuary.",
    noStories: "No inspiration stories published yet.",
    noStoriesSub: "Our designers are busy writing for you!",
    consultDesigners: "Consult our designers",
    namePlaceholder: "e.g. Abdullah Al Mamun",
    phonePlaceholder: "01XXXXXXXXX",
    districtPlaceholder: "Select your district",
    addressPlaceholder: "House, road, area...",
    trxPlaceholder: "Transaction ID",
    paymentNumberPlaceholder: "Your Payment Number",
    // Auth & Reviews
    login: "Login",
    signup: "Sign Up",
    logout: "Logout",
    noAccount: "Don't have an account?",
    alreadyAccount: "Already have an account?",
    createAccount: "Create Account",
    email: "Email Address",
    password: "Password",
    writeReview: "Write a Review",
    submitReview: "Submit Review",
    loginToReview: "Please login to write a review",
    reviewSuccess: "Review submitted successfully!",
    rating: "Rating",
    comment: "Comment",
    adminPortal: "Admin Portal",
    whatClientsSay: "What Our Clients Say"
  },
  bn: {
    home: "হোম",
    shop: "শপ",
    blog: "ব্লগ",
    about: "আমাদের সম্পর্কে",
    contact: "যোগাযোগ",
    cart: "কার্ট",
    wishlist: "উইশলিস্ট",
    addToCart: "কার্টে যোগ করুন",
    buyNow: "এখনই কিনুন",
    newArrival: "নতুন পণ্য",
    offer: "অফার",
    bestSellers: "সেরা পণ্য",
    newArrivals: "নতুন কালেকশন",
    categories: "বিভাগসমূহ",
    allProducts: "সব পণ্য",
    searchPlaceholder: "পণ্য খুঁজুন...",
    sortBy: "সাজান",
    newest: "নতুনগুলো আগে",
    priceLowHigh: "মূল্য: কম থেকে বেশি",
    priceHighLow: "মূল্য: বেশি থেকে কম",
    subtotal: "উপমোট",
    shipping: "শিপিং",
    orderTotal: "মোট মূল্য",
    confirmOrder: "অর্ডার নিশ্চিত করুন",
    insideDhaka: "ঢাকার ভেতরে",
    outsideDhaka: "ঢাকার বাইরে",
    customerReview: "ক্রেতার মতামত",
    description: "বর্ণনা",
    deliveryInfo: "ডেলিভারি তথ্য",
    save: "সঞ্চয়",
    saveMoney: "সাশ্রয় ৳",
    backToBrowsing: "আবার দেখুন",
    youMayAlsoLike: "আপনার ভালো লাগতে পারে",
    viewAll: "সব দেখুন",
    heroBadge: "নতুন কালেকশন ২০২৫",
    heroTitle: "আপনার ঘরকে আলোকিত করুন",
    heroSubtitle: "প্রিমিয়াম লাইটিং এবং ডেকোরের একটি কিউরেটেড কালেকশন যা প্রতিটি বাড়িকে একটি স্বপ্নের বাড়িতে পরিণত করে।",
    shopNow: "এখনই কিনুন",
    ourStory: "আমাদের কথা",
    fastDelivery: "দ্রুত ডেলিভারি",
    acrossBD: "সারা বাংলাদেশে",
    qualityMaterials: "উন্নত মানের পণ্য",
    handpicked: "বাছাই করা পণ্য",
    happyCustomers: "সন্তুষ্ট ক্রেতা",
    satisfaction: "শতভাগ নিশ্চয়তা",
    whyChoose: "কেন ব্রাইটিফাই বিডি?",
    learnMore: "আরও জানুন",
    readMore: "আরও পড়ুন",
    readyToTransform: "আপনার ঘর সাজাতে প্রস্তুত তো?",
    browseCollection: "কালেকশন দেখুন",
    getInTouch: "যোগাযোগ করুন",
    ourCollection: "আমাদের কালেকশন",
    discoveryText: "আপনার ঘরের জন্য সেরা ডেকোরেশন পণ্যগুলো খুঁজে নিন।",
    noProductsFound: "আপনার ফিল্টারের সাথে মিলে এমন কোনো পণ্য পাওয়া যায়নি।",
    clearFilters: "সব ফিল্টার মুছুন",
    shoppingCart: "শপিং কার্ট",
    emptyCart: "আপনার কার্ট খালি",
    emptyCartText: "মনে হচ্ছে আপনি এখনও আপনার কার্টে কোনো পণ্য যোগ করেননি।",
    emptyWishlist: "আপনার উইশলিস্ট খালি",
    emptyWishlistText: "আপনার প্রিয় পণ্যগুলো এখানে সংরক্ষণ করুন যাতে পরে সহজে খুঁজে পান।",
    startShopping: "শপিং শুরু করুন",
    orderDetails: "অর্ডারের বিবরণ",
    fullName: "পুরো নাম",
    phoneNumber: "ফোন নম্বর",
    district: "জেলা",
    fullAddress: "পুরো ঠিকানা",
    paymentMethod: "পেমেন্ট পদ্ধতি",
    cod: "ক্যাশ অন ডেলিভারি",
    bkash: "বিকাশ",
    nagad: "নগদ",
    sendMoneyTo: "অনুগ্রহ করে এই নম্বরে মানি সেন্ড করুন",
    verifyTransaction: "আমাদের টিম খুব শীঘ্রই আপনার ট্রানজেকশন যাচাই করবে।",
    orderPlaced: "অর্ডার সফলভাবে সম্পন্ন হয়েছে!",
    orderPlacedText: "আমাদের সাথে কেনাকাটা করার জন্য ধন্যবাদ। আমরা আপনার অর্ডার পেয়েছি এবং শীঘ্রই আপনার সাথে যোগাযোগ করব।",
    backToShop: "শপে ফিরে যান",
    productNotFound: "পণ্য পাওয়া যায়নি",
    productNotFoundText: "আপনি যে পণ্যটি খুঁজছেন তা সরানো বা মুছে ফেলা হয়েছে।",
    reviewsCount: "মতামত",
    postedBy: "লিখেছেন",
    on: "তারিখ",
    shippingInfo: "শিপিং তথ্য",
    note: "দ্রষ্টব্য",
    fragileNote: "ডোম এবং আয়নার মতো ভঙ্গুর পণ্যগুলো অতিরিক্ত যত্নের সাথে এবং মাল্টি-লেয়ার বাবল র‍্যাপিংয়ের মাধ্যমে পাঠানো হয় যাতে তা আপনার কাছে নিখুঁতভাবে পৌঁছায়।",
    getInTouchText: "আমাদের ডেকোর সম্পর্কে কোনো প্রশ্ন আছে? আমাদের বিশেষজ্ঞরা আপনার স্বপ্নের ঘর সাজাতে সাহায্য করতে প্রস্তুত।",
    contactInfo: "যোগাযোগের তথ্য",
    phoneLabel: "ফোন",
    emailLabel: "ইমেইল",
    officeAddress: "অফিসের ঠিকানা",
    nameLabel: "নাম",
    messageLabel: "বার্তা",
    sending: "পাঠানো হচ্ছে...",
    sendMessage: "বার্তা পাঠান",
    messageSent: "বার্তা পাঠানো হয়েছে!",
    messageSentText: "আমরা আপনার বার্তা পেয়েছি এবং আগামী ২৪ ঘণ্টার মধ্যে আপনার সাথে যোগাযোগ করব।",
    sendAnother: "অন্য বার্তা পাঠান",
    aboutTitle: "ব্রাইটিফাই বিডি সম্পর্কে",
    aboutText: "আমরা ঢাকা ভিত্তিক একটি প্রিমিয়াম হোম ডেকোরেশন স্টোর। আমাদের লক্ষ্য হলো কিউরেটেড ডিজাইন এবং উচ্চমানের উপকরণের মাধ্যমে আপনার ঘরের প্রতিটি কোণে আভিজাত্য এবং আলো নিয়ে আসা।",
    inspirationTitle: "অনুপ্রেরণা ও ডিজাইন",
    inspirationSubtitle: "আপনার ঘরকে স্বর্গ করে গড়ে তুলতে বিশেষজ্ঞ টিপস এবং গল্প।",
    noStories: "এখনও কোনো গল্প প্রকাশিত হয়নি।",
    noStoriesSub: "আমাদের ডিজাইনাররা আপনার জন্য লিখতে ব্যস্ত!",
    consultDesigners: "আমাদের ডিজাইনারদের পরামর্শ নিন",
    namePlaceholder: "যেমন: আবদুল্লাহ আল মামুন",
    phonePlaceholder: "০১XXXXXXXXX",
    districtPlaceholder: "আপনার জেলা নির্বাচন করুন",
    addressPlaceholder: "বাসা নং, রোড, এলাকা...",
    trxPlaceholder: "ট্রানজেকশন আইডি",
    paymentNumberPlaceholder: "আপনার পেমেন্ট নম্বর",
    // Auth & Reviews (Bangla)
    login: "লগইন",
    signup: "সাইন আপ",
    logout: "লগআউট",
    noAccount: "অ্যাকাউন্ট নেই?",
    alreadyAccount: "ইতিমধ্যে অ্যাকাউন্ট আছে?",
    createAccount: "অ্যাকাউন্ট তৈরি করুন",
    email: "ইমেইল ঠিকানা",
    password: "পাসওয়ার্ড",
    writeReview: "মতামত লিখুন",
    submitReview: "মতামত জমা দিন",
    loginToReview: "মতামত দিতে লগইন করুন",
    reviewSuccess: "মতামত সফলভাবে জমা হয়েছে!",
    rating: "রেটিং",
    comment: "মন্তব্য",
    adminPortal: "অ্যাডমিন পোর্টাল",
    whatClientsSay: "আমাদের সম্পর্কে ক্রেতাদের মতামত"
  }
};

export const BANGLADESH_DISTRICTS = [
  { en: "Bagerhat", bn: "বাগেরহাট" },
  { en: "Bandarban", bn: "বান্দরবান" },
  { en: "Barguna", bn: "বরগুনা" },
  { en: "Barishal", bn: "বরিশাল" },
  { en: "Bhola", bn: "ভোলা" },
  { en: "Bogra", bn: "বগুড়া" },
  { en: "Brahmanbaria", bn: "ব্রাহ্মণবাড়িয়া" },
  { en: "Chandpur", bn: "চাঁদপুর" },
  { en: "Chapai Nawabganj", bn: "চাঁপাইনবাবগঞ্জ" },
  { en: "Chattogram", bn: "চট্টগ্রাম" },
  { en: "Chuadanga", bn: "চুয়াডাঙ্গা" },
  { en: "Cumilla", bn: "কুমিল্লা" },
  { en: "Cox's Bazar", bn: "কক্সবাজার" },
  { en: "Dhaka", bn: "ঢাকা" },
  { en: "Dinajpur", bn: "দিনাজপুর" },
  { en: "Faridpur", bn: "ফরিদপুর" },
  { en: "Feni", bn: "ফেনী" },
  { en: "Gaibandha", bn: "গাইবান্ধা" },
  { en: "Gazipur", bn: "গাজীপুর" },
  { en: "Gopalganj", bn: "গোপালগঞ্জ" },
  { en: "Habiganj", bn: "হবিগঞ্জ" },
  { en: "Jamalpur", bn: "জামালপুর" },
  { en: "Jashore", bn: "যশোর" },
  { en: "Jhalokathi", bn: "ঝালকাঠি" },
  { en: "Jhenaidah", bn: "ঝিনাইদহ" },
  { en: "Joypurhat", bn: "জয়পুরহাট" },
  { en: "Khagrachari", bn: "খাগড়াছড়ি" },
  { en: "Khulna", bn: "খুলনা" },
  { en: "Kishoreganj", bn: "কিশোরগঞ্জ" },
  { en: "Kurigram", bn: "কুড়িগ্রাম" },
  { en: "Kushtia", bn: "কুষ্টিয়া" },
  { en: "Lakshmipur", bn: "লক্ষ্মীপুর" },
  { en: "Lalmonirhat", bn: "লালমনিরহাট" },
  { en: "Madaripur", bn: "মাদারীপুর" },
  { en: "Magura", bn: "মাগুরা" },
  { en: "Manikganj", bn: "মানিকগঞ্জ" },
  { en: "Meherpur", bn: "মেহেরপুর" },
  { en: "Moulvibazar", bn: "মৌলভীবাজার" },
  { en: "Munshiganj", bn: "মুন্সীগঞ্জ" },
  { en: "Mymensingh", bn: "ময়মনসিংহ" },
  { en: "Naogaon", bn: "নওগাঁ" },
  { en: "Narail", bn: "নড়াইল" },
  { en: "Narayanganj", bn: "নারায়ণগঞ্জ" },
  { en: "Narsingdi", bn: "নরসিংদী" },
  { en: "Natore", bn: "নাটোর" },
  { en: "Netrokona", bn: "নেত্রকোণা" },
  { en: "Nilphamari", bn: "নীলফামারী" },
  { en: "Noakhali", bn: "নোয়াখালী" },
  { en: "Pabna", bn: "পাবনা" },
  { en: "Panchagarh", bn: "পঞ্চগড়" },
  { en: "Patuakhali", bn: "পটুয়াখালী" },
  { en: "Pirojpur", bn: "পিরোজপুর" },
  { en: "Rajbari", bn: "রাজবাড়ী" },
  { en: "Rajshahi", bn: "রাজশাহী" },
  { en: "Rangamati", bn: "রাঙ্গামাটি" },
  { en: "Rangpur", bn: "রংপুর" },
  { en: "Satkhira", bn: "সাতক্ষীরা" },
  { en: "Shariatpur", bn: "শরীয়তপুর" },
  { en: "Sherpur", bn: "শেরপুর" },
  { en: "Sirajganj", bn: "সিরাজগঞ্জ" },
  { en: "Sunamganj", bn: "সুনামগঞ্জ" },
  { en: "Sylhet", bn: "সিলেট" },
  { en: "Tangail", bn: "টাঙ্গাইল" },
  { en: "Thakurgaon", bn: "ঠাকুরগাঁও" }
].sort((a, b) => a.en.localeCompare(b.en));

export const INITIAL_PRODUCTS: Product[] = [
  // LIGHTING
  {
    id: '1',
    name: 'Eternal Rose LED String Lights',
    price: 1200,
    salePrice: 950,
    description: 'Beautifully crafted LED rose string lights that bring a magical glow to any room. Perfect for bedrooms, weddings, or festive decorations.',
    category: 'Lighting',
    images: ['https://i.ibb.co/VYd8K4g/product-1.jpg', 'https://i.ibb.co/Vq8sYtV/product-2.jpg'],
    stock: 50,
    isFeatured: true,
    isNewArrival: true,
    tags: ['roses', 'led', 'romantic'],
    slug: 'eternal-rose-led-lights',
    reviews: [
      { id: 'rev1', userId: 'u1', userName: 'Lily Feliciano', rating: 5, comment: "I'm really happy with my order. It adds such a soft atmosphere to my bedroom.", date: '31/05/2023' }
    ]
  },
  {
    id: '2',
    name: 'Celestial Star & Moon Curtain',
    price: 1800,
    salePrice: 1550,
    description: 'Transform your windows into a galaxy with these warm white star and moon curtain lights. Features 138 LEDs and 8 flashing modes.',
    category: 'Lighting',
    images: ['https://i.ibb.co/zXn2H1B/product-3.jpg', 'https://i.ibb.co/N7x1n9v/product-4.jpg'],
    stock: 30,
    isFeatured: true,
    isNewArrival: false,
    tags: ['stars', 'curtain', 'warm-white'],
    slug: 'celestial-star-moon-curtain',
    reviews: []
  },
  {
    id: '3',
    name: 'Modern Glass Dome Table Lamp',
    price: 2500,
    salePrice: 2100,
    description: 'A minimalist masterpiece featuring a clear hand-blown glass dome over an elegant metallic base. Perfect for bedside or office staging.',
    category: 'Lighting',
    images: ['https://images.unsplash.com/photo-1534073828943-f801091bb18c?q=80&w=800&auto=format&fit=crop'],
    stock: 15,
    isFeatured: false,
    isNewArrival: true,
    tags: ['modern', 'lamp', 'minimalist'],
    slug: 'modern-glass-dome-lamp',
    reviews: []
  },
  // WALL DECOR
  {
    id: '4',
    name: 'Abstract Gold Foil Canvas Art',
    price: 3800,
    salePrice: 3200,
    description: 'Premium hand-painted abstract canvas featuring real gold foil accents. This 24x36 piece adds instant luxury to your living room walls.',
    category: 'Wall Decor',
    images: ['https://images.unsplash.com/photo-1513519245088-0e12902e5a38?q=80&w=800&auto=format&fit=crop'],
    stock: 10,
    isFeatured: true,
    isNewArrival: true,
    tags: ['art', 'gold', 'canvas'],
    slug: 'abstract-gold-foil-art',
    reviews: []
  },
  {
    id: '5',
    name: 'Hexagon Mirror Wall Set',
    price: 1500,
    salePrice: 1250,
    description: 'A set of 12 adhesive acrylic hexagon mirrors that can be arranged in any pattern. Reflect light and create the illusion of a larger space.',
    category: 'Wall Decor',
    images: ['https://images.unsplash.com/photo-1618220179428-22790b461013?q=80&w=800&auto=format&fit=crop'],
    stock: 40,
    isFeatured: false,
    isNewArrival: false,
    tags: ['mirror', 'decor', 'geometric'],
    slug: 'hexagon-mirror-set',
    reviews: []
  },
  // FURNITURE ACCENTS
  {
    id: '6',
    name: 'Emerald Velvet Ottoman',
    price: 5500,
    salePrice: 4800,
    description: 'Luxurious emerald green velvet footstool with gold-finished stainless steel legs. A statement piece that doubles as extra seating.',
    category: 'Furniture Accents',
    images: ['https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=800&auto=format&fit=crop'],
    stock: 5,
    isFeatured: true,
    isNewArrival: true,
    tags: ['furniture', 'velvet', 'luxury'],
    slug: 'emerald-velvet-ottoman',
    reviews: []
  },
  // ACCESSORIES
  {
    id: '7',
    name: 'Nordic Ceramic Vase Set',
    price: 2200,
    salePrice: 1850,
    description: 'Set of 3 matte finish ceramic vases in varying heights. Perfect for dried flowers or as standalone sculptural pieces.',
    category: 'Accessories',
    images: ['https://images.unsplash.com/photo-1581783898377-1c85bf937427?q=80&w=800&auto=format&fit=crop'],
    stock: 25,
    isFeatured: false,
    isNewArrival: true,
    tags: ['ceramic', 'nordic', 'vases'],
    slug: 'nordic-ceramic-vase-set',
    reviews: []
  },
  {
    id: '8',
    name: 'Aromatic Scented Candle Set',
    price: 950,
    salePrice: 750,
    description: 'Hand-poured soy wax candles in three signature scents: Lavender Dream, Sandalwood Mist, and Ocean Breeze. Comes in recycled glass jars.',
    category: 'Accessories',
    images: ['https://images.unsplash.com/photo-1603006905003-be475563bc59?q=80&w=800&auto=format&fit=crop'],
    stock: 60,
    isFeatured: false,
    isNewArrival: false,
    tags: ['candles', 'scent', 'home-office'],
    slug: 'aromatic-scented-candle-set',
    reviews: []
  }
];

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'c1', name: 'Lighting', slug: 'lighting', image: 'https://images.unsplash.com/photo-1540932239986-30128078f3c5?auto=format&fit=crop&q=80&w=400' },
  { id: 'c2', name: 'Wall Decor', slug: 'wall-decor', image: 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&get=80&w=400' },
  { id: 'c3', name: 'Furniture Accents', slug: 'furniture', image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&q=80&w=400' },
  { id: 'c4', name: 'Accessories', slug: 'accessories', image: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&q=80&w=400' }
];

export const INITIAL_BLOG_POSTS: BlogPost[] = [
  {
    id: 'b1',
    title: '5 Ways to Brighten Your Living Room',
    excerpt: 'Light is the soul of a home. Discover how small changes can make a big impact on your mood.',
    content: 'Light is the soul of a home. Discover how small changes can make a big impact. From changing bulbs to adding accent lighting, we explore it all. Start by identifying the dark corners in your room and placing a floor lamp or wall sconce to draw the eye. Layering light—using overhead, task, and ambient lighting together—creates depth and warmth.',
    author: 'Admin',
    date: '20/03/2024',
    images: ['https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&q=80&w=800'],
    slug: '5-ways-to-brighten-living-room',
    tags: ['Interior Design', 'Lighting']
  },
  {
    id: 'b2',
    title: 'Small Space Magic: Decorating Apartments',
    excerpt: 'Living in a studio? Don\'t sacrifice style. Here is how to maximize every square inch.',
    content: 'Living in a small apartment doesn\'t mean you can\'t have a beautiful home. Use mirrors to reflect light and create the illusion of depth. Choose multi-functional furniture like ottomans that store blankets or tables that fold away. Keep the color palette light and airy to prevent the space from feeling cramped.',
    author: 'Sarah Jenkins',
    date: '15/04/2024',
    images: ['https://images.unsplash.com/photo-1536376074432-bf1217e71f4a?auto=format&fit=crop&q=80&w=800'],
    slug: 'small-space-magic-apartments',
    tags: ['Apartment Living', 'Space Saving']
  },
  {
    id: 'b3',
    title: 'The Power of Texture in Interior Design',
    excerpt: 'Why the way things "feel" is just as important as how they look in your home.',
    content: 'Texture is the secret ingredient that professional designers use to make a room feel complete. Mix rough textures like burlap or natural wood with smooth surfaces like velvet or silk. In a monochrome room, texture is what provides visual interest and prevents the space from looking flat and uninviting.',
    author: 'Admin',
    date: '02/05/2024',
    images: ['https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&q=80&w=800'],
    slug: 'power-of-texture-interior-design',
    tags: ['Design Principles', 'Styling']
  },
  {
    id: 'b4',
    title: 'Cozy Corners: Styling an Unused Nook',
    excerpt: 'Transform that awkward corner under the stairs into your favorite reading spot.',
    content: 'Every home has those awkward "dead" spaces. A comfortable chair, a small side table, and a dedicated task light can turn a corner into a sanctuary. Add a plush rug and a couple of your favorite books to make it inviting. It is about creating "zones" within your home for different activities.',
    author: 'Ahmed Rezwan',
    date: '12/06/2024',
    images: ['https://images.unsplash.com/photo-1617103996702-96ff29b1c467?auto=format&fit=crop&q=80&w=800'],
    slug: 'cozy-corners-styling-nooks',
    tags: ['DIY', 'Home Sanctuary']
  },
  {
    id: 'b5',
    title: 'Trends of 2025: What is Next in Home Decor',
    excerpt: 'From sustainable materials to high-tech lighting, see what will be trending next year.',
    content: 'As we move into 2025, the focus is shifting towards sustainable, recycled materials and biophilic design. Bringing the outside in with plants and natural stones is bigger than ever. We are also seeing a rise in smart lighting that adjusts its color temperature based on the time of day to match our circadian rhythms.',
    author: 'Admin',
    date: '01/07/2024',
    images: ['https://images.unsplash.com/photo-1615873968403-89e068628265?auto=format&fit=crop&q=80&w=800'],
    slug: 'trends-2025-home-decor',
    tags: ['Trends', 'Future Living']
  }
];

export const INITIAL_TESTIMONIALS: Testimonial[] = [
  { id: 't1', name: 'Sara Khan', role: 'Homemaker', content: 'The lights from Brightify BD changed the entire vibe of my bedroom. Absolutely love the quality!', rating: 5, avatar: 'https://i.pravatar.cc/150?u=sara' },
  { id: 't2', name: 'Ahmed Rezwan', role: 'Architect', content: 'Premium finishing and very fast delivery. Highly recommended for home staging.', rating: 5, avatar: 'https://i.pravatar.cc/150?u=ahmed' },
  { id: 't3', name: 'Nusrat Jahan', role: 'Interior Designer', content: 'As a professional, I highly value the aesthetic and quality of Brightify items. They truly elevate space.', rating: 5, avatar: 'https://i.pravatar.cc/150?u=nusrat' },
  { id: 't4', name: 'Zayed Ali', role: 'Home Owner', content: 'Customer service was very responsive. The packing was so secure for the glass domes I ordered.', rating: 5, avatar: 'https://i.pravatar.cc/150?u=zayed' }
];

export const INITIAL_SETTINGS: AppSettings = {
  siteName: 'Brightify BD',
  logoUrl: 'https://i.ibb.co/v4ynLLwk/logo.jpg',
  heroImage: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80&w=2000&auto=format&fit=crop',
  primaryColor: '#7c3aed',
  contactEmail: 'info@brightifybd.com',
  phoneNumber: '+880 1711 111111',
  bkashNumber: '01700000000',
  nagadNumber: '01900000000',
  address: 'Gulshan, Dhaka, Bangladesh',
  facebookUrl: 'https://www.facebook.com/BrightifyBD',
  showPromoBanner: true,
  promoText: 'Ramadan Special: Up to 25% Off on All Lighting!',
  adminPassword: 'admin',
  moderators: []
};
